### ISSUE TITLE
NonExistentEventException: Events are no longer supported by dash.

### ISSUE THREAD

**Issue by antoan** [freshwuzhere/react-player-dash#2]
Hi there, 

I get the above exception when I import the react-player-dash, this is because Events were removed from dash-core-components as of [0.43.1] - 2019-02-11
https://github.com/plotly/dash/issues/531
https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md

I was wondering if you know of a quick way to fix this, the only direct references to Events I came across in the code were in the demo python scripts included: usage.py and video_demo.py?

**Comment by freshwuzhere** [comment]
Hi ,

I haven’t looked at this in a while - and there is a MUCH better version of this located at 

https://community.plot.ly/t/dash-player-custom-component-playing-and-controlling-your-videos-with-dash/12349 <https://community.plot.ly/t/dash-player-custom-component-playing-and-controlling-your-videos-with-dash/12349>


Much better than mine I think.  If you want to use mine for some reason let me know - I’ll fix the Events part.

Ian

On 12 Feb 2019, at 04:39, antoan <notifications@github.com> wrote:

Hi there,

I get the above exception when I import the react-player-dash, this is because Events were removed from dash-core-components as of [0.43.1] - 2019-02-11
plotly/dash#531 <https://github.com/plotly/dash/issues/531>
https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md <https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md>
I was wondering if you know of a quick way to fix this, the only direct references to Events I came across in the code were in the demo python scripts included: usage.py and video_demo.py?

**Comment by antoan** [comment]
Thanks very much for the heads up, I'll give that a try.
